# Project information
site_name: 'Adarsh notes'
site_description: 'Adarsh notes'
site_author: 'peachpie'
site_url: 'https://dliproj.github.io/notes'

# Repository
repo_name: 'peachpiecompiler/peachpie'
repo_url: 'https://github.com/DLIProj/notes'
edit_uri: 'https://github.com/DLIProj/notes/edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2021 iolevel s.r.o.'

# Configuration
theme:
  name: 'material'
  custom_dir: 'custom_theme'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  icon:
    logo: material/home
    repo: fontawesome/brands/github
  favicon: img/favicon.ico
  logo: img/logo.png
  features:
    - tabs
    - instant

    
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

# Customization
extra_css:
  - extra.css

extra:
  social:
    - icon: material/home
      link: 'https://www.peachpie.io/'
    - icon: fontawesome/brands/github
      link: 'https://github.com/peachpiecompiler/peachpie'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/pchpcompiler'

# Google Analytics

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.progressbar
  - codehilite:
      guess_lang: false
  - toc:
      permalink: "#"

# plugins
plugins:
    - search:
        lang:
          - en
    - awesome-pages
